@startuml FolderStructure

!unquoted procedure Folder($name)
<&folder> $name
!endprocedure
salt
{
{T
+FolerName                | Description
+ Folder(JWScheduler)     | Main Folder
++ Folder(Documentation)  | All Documentation and UML diagrams
+++ Folder(PlantUML)      | UML diagram source
++ Folder(3rdParty)       | All 3rd party projects
++ Folder(Framework)      | Framework code 
+++ Folder(Framework.Core) | Core framework helper code
+++ Folder(Framework.WPF.Core) | Core framework helper code for WPF
+++ Folder(Framework.Logging.Core) | Core framework helper code for logging
++ Folder(Source)         | Source code specific to this application
+++ Folder(JWScheduler)       | Solution File and Main App.xaml
++ Folder(Build)          | Build tools
}
}
@enduml